name: CI/CD Test Pipeline (OIDC)

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # OIDC 토큰 발급에 필수
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. AWS OIDC 인증
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ROLE_ASSUME }}
          aws-region: ap-northeast-2

      # 3. Docker 빌드
      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .

      # 4. Docker 푸시
      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
          docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
